### ISSUE TITLE
Custom ranges breaks linked calendars

### ISSUE THREAD

**Issue by RyanHow** [fetrarij/ngx-daterangepicker-material#180]
Hi,

Nice date range picker components :)

I'm having an issue with the custom ranged with lilnked calendars.

Usually the calendars show one month, then the next month on the next calendar. But if I set the custom range to "today", then both the calendars are set to the same month.

Then changing the month on the calendar changes both calendars (so they are both locked on the same month)

You can kind of see it here:

![image](https://user-images.githubusercontent.com/4535791/62674748-5e6f4080-b9d6-11e9-9743-0e55cf9af566.png)

If it could set the 2nd calendar to the selected month, then change the 1st calendar to the previous month, that would be ideal!

Thanks :)

**Comment by RyanHow** [comment]
I just noticed, also for large date ranges (such as 1 year), it sets the first calendar to the start and the second calendar to the end of the range.

So it also breaks the linked calendars.

**Comment by fetrarij** [comment]
Hello @RyanHow , thanks for reporting the bug.

**Comment by luguiant** [comment]
Is there anything new about it?

**Comment by luguiant** [comment]
I think that the problem does not only happen with the first rank, without having a range of one month I also believe that it would happen, that is if we are at November 30 and we selected last 30 days, the bug should also happen or I think so, I would have to There is some way to do this test, and in case this bug also occurs, we would know that this happens if the range is contained within the current month, it would be a way to rule out these rare cases of error.

If someone has already managed to find the solution to this problem, I would be grateful if you could inform us how I achieved it, I really need to have a solution to this peculiar bug.
